### ISSUE TITLE
一加5 Android10 demo闪退

### ISSUE THREAD

**Issue by iBingo** [liujingxing/Indicator#1]

**Comment by iBingo** [comment]
2024-01-02 20:24:19.851  8300-8300  AndroidRuntime          com.ljx.indicator                    E  FATAL EXCEPTION: main
                                                                                                    Process: com.ljx.indicator, PID: 8300
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ljx.indicator/com.ljx.indicator.IndicatorActivity}: android.view.InflateException: Binary XML file line #56 in com.ljx.indicator:layout/indicator_layout: Binary XML file line #56 in com.ljx.indicator:layout/indicator_layout: Error inflating class com.ljx.view.IndicatorView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3375)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7697)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #56 in com.ljx.indicator:layout/indicator_layout: Binary XML file line #56 in com.ljx.indicator:layout/indicator_layout: Error inflating class com.ljx.view.IndicatorView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #56 in com.ljx.indicator:layout/indicator_layout: Error inflating class com.ljx.view.IndicatorView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
                                                                                                    	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:470)
                                                                                                    	at android.app.Activity.setContentView(Activity.java:3337)
                                                                                                    	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:464)
                                                                                                    	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
                                                                                                    	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
                                                                                                    	at com.ljx.indicator.IndicatorActivity.onCreate(IndicatorActivity.kt:31)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7815)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7804)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7697)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
2024-01-02 20:24:19.851  8300-8300  AndroidRuntime          com.ljx.indicator                    E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
                                                                                                    	at com.ljx.view.IndicatorView.<init>(IndicatorView.kt:82)
                                                                                                    	at com.ljx.view.IndicatorView.<init>(IndicatorView.kt:25)
                                                                                                    	at com.ljx.view.IndicatorView.<init>(Unknown Source:11)
                                                                                                    	... 33 more

**Comment by liujingxing** [comment]
更新至1.0.2版本就好

**Comment by liujingxing** [comment]
哦，demo啊，我更新下

**Comment by liujingxing** [comment]
重新下载apk即可

**Comment by iBingo** [comment]
> 重新下载apk即可

安装了下，Android10还是崩溃的，Android14是正常的

**Comment by liujingxing** [comment]
下载代码，跑起来试试，apk可能有缓存

**Comment by liujingxing** [comment]
> AutoCloseable

因为android 14上，TypeArray对象实现了AutoCloseable接口

**Comment by iBingo** [comment]
> > AutoCloseable
> 
> 因为android 14上，TypeArray对象实现了AutoCloseable接口

拉demo代码直接运行正常
